# Generated by Django 4.2.1 on 2023-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_total_review_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank='True', default='default.jpg', null=True, upload_to=''),
        ),
    ]
